### ISSUE TITLE
BUG: Foundation Maven Plugins MDA Maven Plugin fails to find all its neccessary dependencies  

### ISSUE THREAD

**Issue by cwoods-cpointe** [boozallen/aissemble#390]
## Description
The build fails on foundation maven plugins `MDA maven plugin` when running without org.apache.maven.plugins:maven-dependency-plugin in the m2.
Failure logs:
```
[ERROR] As an aiSSEMBLE user, I want pipeline artifacts derived from MDA models so I don't have to manually manage the pom.Discover python data-record artifacts -- Time elapsed: 0.178 s <<< ERROR!
java.lang.RuntimeException: Failed to configure the Pipeline Artifacts Mojo and read in the pipeline models
	at com.boozallen.mda.maven.PipelineTest.the_copy_pipeline_artifacts_goal_is_run(PipelineTest.java:153)
Caused by: java.lang.RuntimeException: Failed to copy JAR for DataDeliverySparkPipeline
	at com.boozallen.mda.maven.util.PipelineArtifactCopier.copyArtifact(PipelineArtifactCopier.java:43)
	...
        ...
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.apache.maven.plugins:maven-dependency-plugin:pom:3.6.1 from/to central (https://repo.maven.apache.org/maven2): No connector factories available
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:521)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:402)
	... 71 more
Caused by: org.eclipse.aether.transfer.NoRepositoryConnectorException: No connector factories available
	at org.eclipse.aether.internal.impl.DefaultRepositoryConnectorProvider.newRepositoryConnector(DefaultRepositoryConnectorProvider.java:167)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:512)
	... 72 more
```

## Steps to Reproduce
1. clear the dependency from your m2 - `rm -rf ~/.m2/repository/org/apache/maven/plugins/`
2. Build MDA maven plugin module - `mvn clean install -Dmaven.build.cache.skipCache -pl :mda-maven-plugin`
4. See test failures

## Expected Behavior
The tests pass and the build succeeds.

## Actual Behavior
The tests fail to complete.

## Additional Context
Github action showing this behavior - https://github.com/boozallen/aissemble/actions/runs/11156774022

**Comment by jaebchoi** [comment]
Did investigation and test passes OBE and fix was in this [PR](https://github.com/boozallen/aissemble/pull/386/files#diff-ba0f62547b163439d39514e44b1a7dc76c97fffcd95f36797894604cfbb3b8a8L111-L113)

closing
