### ISSUE TITLE
BUG: Build fails when unneeded dependency is removed

### ISSUE THREAD

**Issue by ewilkins-csi** [boozallen/aissemble#451]
## Description
The JBoss RESTEasy client version set in the bom-component is incompatible with some other libraries.  This isn't noticeable with a default project, because the `extensions-authzforce` dependency is always added to pipeline POMs even when it isn't needed. However, removing that unneeded dependency ends up rolling the REST Easy client back to an incompatible version.

## Steps to Reproduce
1. Create a downstream project with a Spark pipeline
2. Generate out the project until the pipeline POM is part of the build
3. Remove the `extensions-authzforce` dependency from the pipeline POM
4. Build the project

## Expected Behavior
The build should not fail because an unused dependency is removed.

## Actual Behavior
The build fails with the unneeded dependency removed.

## Definition of Done
 - Update JBoss REST Easy version in parent POM to compatible version
 - The bom-component is totally removed and the above steps to reproduce do not cause an `AbstractMethodError`
--- Stretch Goal ---
 - When alerting is enabled for a pipeline step, the `foundation-alerting` dependency is added to the pipeline POM

## Test Steps
1. Create a new project
```sh
mvn archetype:generate '-DarchetypeGroupId=com.boozallen.aissemble' \
                       '-DarchetypeArtifactId=foundation-archetype' \
                       '-DarchetypeVersion=1.10.0-SNAPSHOT' \
                       '-DgroupId=org.test' \
                       '-Dpackage=org.test' \
                       '-DprojectGitUrl=test.org/test.git' \
                       '-DprojectName=Test Project' \
                       '-DartifactId=final-451' \
&& cd final-451
```
2. Copy [SparkPipeline.json](https://github.com/user-attachments/files/17620771/SparkPipeline.json) into _final-451-pipeline-models/src/main/resources/pipelines_
3. Run the build once and follow manual actions
4. Edit _final-451-pipelines/spark-pipeline/pom.xml_ and remove the following dependency:
```xml
<dependency>
     <groupId>com.boozallen.aissemble</groupId>
     <artifactId>extensions-authzforce</artifactId>
</dependency>
```
5. Build the project again and verify the pipeline tests pass without errors:
```sh
08:50:19 [INFO] --- surefire:3.5.0:test (default-test) @ spark-pipeline ---
08:50:19 [INFO] Using auto detected provider org.apache.maven.surefire.junit4.JUnit4Provider
08:50:19 [INFO] 
08:50:19 [INFO] -------------------------------------------------------
08:50:19 [INFO]  T E S T S
08:50:19 [INFO] -------------------------------------------------------
...
08:50:25 [INFO] Results:
08:50:25 [INFO] 
08:50:25 [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
```

## Additional Context
Root cause stacktrace:
```sh
Caused by: java.lang.AbstractMethodError: Receiver class org.jboss.resteasy.microprofile.config.ServletConfigSource does not define or inherit an implementation of the resolved method 'abstract java.util.Set getPropertyNames()' of interface org.eclipse.microprofile.config.spi.ConfigSource.
	at io.smallrye.config.SmallRyeConfigSources$ConfigValueConfigSourceWrapper.getPropertyNames(SmallRyeConfigSources.java:106)
	at io.smallrye.config.SmallRyeConfigSources.iterateNames(SmallRyeConfigSources.java:48)
	at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.iterateNames(SmallRyeConfigSourceInterceptorContext.java:46)
	at io.smallrye.config.SecretKeysConfigSourceInterceptor.iterateNames(SecretKeysConfigSourceInterceptor.java:33)
	at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.iterateNames(SmallRyeConfigSourceInterceptorContext.java:46)
	at io.smallrye.config.SmallRyeConfigBuilder$2.getInterceptor(SmallRyeConfigBuilder.java:272)
	at io.smallrye.config.SmallRyeConfigBuilder$InterceptorWithPriority.getInterceptor(SmallRyeConfigBuilder.java:819)
	at io.smallrye.config.SmallRyeConfig$ConfigSources.<init>(SmallRyeConfig.java:794)
	at io.smallrye.config.SmallRyeConfig.<init>(SmallRyeConfig.java:86)
	at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:736)
	at io.smallrye.config.SmallRyeConfigFactory$Default.getConfigFor(SmallRyeConfigFactory.java:63)
	at io.smallrye.config.SmallRyeConfigProviderResolver.getConfig(SmallRyeConfigProviderResolver.java:78)
	at org.eclipse.microprofile.config.ConfigProvider.getConfig(ConfigProvider.java:101)
	at io.smallrye.config.inject.ConfigExtension.validate(ConfigExtension.java:186)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:99)
	... 38 more
```

**Comment by ewilkins-csi** [comment]
**DoD** with @carter-cundiff

**Comment by ewilkins-csi** [comment]
**OTS** with @nartieri

**Comment by carter-cundiff** [comment]
Testing passed:
![image](https://github.com/user-attachments/assets/5bb95a04-e6b9-4ee5-89b0-780a66541f5e)
